tests:
  stage: test
  tags:
    - python
  script:
    - pip3 install -r requirements.txt
    - pip3 install -r dev-only-reqs.txt
    - pycodestyle --ignore=E501,W503,E121,E123,E126,E133,E226,E241,E242,E704 .
    - python3 -m tests.test_xml
