%
% Generated by flexscore.php on 2018-11-30 13:34:43
%
% Score configuration:
% <?xml version="1.0"?>
% <BulletinHarmony>
%   <instrument>BulletinHarmony</instrument>
%   <staff3>ta-scc-acc</staff3>
%   <staff4>ba-tcc-bcc</staff4>
%   <stanzas>all</stanzas>
%   <showHymnNumber>false</showHymnNumber>
%   <showMeasureNumbers>false</showMeasureNumbers>
%   <showVocalMarkup>true</showVocalMarkup>
%   <staffSize>20</staffSize>
%   <lyricSize>1</lyricSize>
%   <paperSize>legal</paperSize>
%   <iPad>false</iPad>
%   <useKeyboard>true</useKeyboard>
%   <includeNotes>false</includeNotes>
%   <showPartNames>false</showPartNames>
%   <lilypond>true</lilypond>
%   <orientation>portrait</orientation>
%   <showSubtitle>true</showSubtitle>
%   <separateDescant>false</separateDescant>
%   <separateStanzas>false</separateStanzas>
%   <autoResizeTitle>true</autoResizeTitle>
%   <maxInlineStanzas>5</maxInlineStanzas>
%   <overflowLyricSize>0</overflowLyricSize>
%   <staff1Name>descant</staff1Name>
%   <staff2Name>chords</staff2Name>
%   <staff3Name>treble</staff3Name>
%   <staff4Name>bass</staff4Name>
%   <staff5Name>percussion</staff5Name>
%   <staff6Name>keyboard</staff6Name>
%   <hymnalID>AAHH2001</hymnalID>
%   <number>120</number>
%   <textHymnalID>AAHH2001</textHymnalID>
%   <textNumber>120</textNumber>
%   <tuneHymnalID>AAHH2001</tuneHymnalID>
%   <tuneNumber>120</tuneNumber>
%   <hymnType>normal_flexscore</hymnType>
%   <hymnID/>
%   <hash>c7dc1c</hash>
%   <hasSoprano>true</hasSoprano>
%   <hasAlto>true</hasAlto>
%   <hasTenor>true</hasTenor>
%   <hasBass>true</hasBass>
%   <useStanzas>StanzaOne StanzaTwo StanzaThree StanzaFour</useStanzas>
%   <inlineStanzas>4</inlineStanzas>
%   <keySignature>gmaj</keySignature>
%   <stanzaSpecificResponseLyrics>false</stanzaSpecificResponseLyrics>
% </BulletinHarmony>
% 
\include "definitions.ly"


%%%%%   text   %%%%%

\header {
   title = \markup { \fontsize #0 "Joyful, Joyful, We Adore You" }
}

StanzaOne = \lyricmode {
  \set stanza = "1"
Joy -- ful, joy -- ful, we a -- dore You, 
God of glo -- ry, Lord of love; 
Hearts un -- fold like flow’rs be -- fore You,
O -- p’ning to the sun a -- bove. 
Melt the clouds of sin and _ sad -- ness; 
Drive the _ dark of doubt a -- way;
Giv -- er of im -- mor -- tal glad -- ness, 
Fill us with the light of day!
}

StanzaTwo = \lyricmode {
  \set stanza = "2"
All Your works with joy sur -- round You, 
Earth and heav’n re -- flect Your rays, 
Stars and an -- gels sing a -- round You,
Cen -- ter of un -- bro -- ken praise; 
Field and for -- est, vale and _ moun -- tain, 
Flow -- ’ry _ mead -- ow, flash -- ing sea,
Chant -- ing bird and flow -- ing foun -- tain,
Prais -- ing You e -- ter -- nal -- ly!
}

StanzaThree = \lyricmode {
  \set stanza = "3"
Al -- ways giv -- ing and for -- giv -- ing, 
Ev -- er bless -- ing, ev -- er blest, 
Well -- spring of the joy of liv -- ing,
O -- cean depth of hap -- py rest! 
Lov -- ing Fa -- ther, Christ our _ Broth -- er, 
Let Your _ light up -- on us shine;
Teach us how to love each oth -- er, 
Lift us to the joy di -- vine.
}

StanzaFour = \lyricmode {
  \set stanza = "4"
Mor -- tals join the might -- y cho -- rus, 
Which the morn -- ing stars be -- gan; 
God’s own love is reign -- ing o’er us,
Join -- ing peo -- ple hand in hand. 
Ev -- er sing -- ing, march we _ on -- ward, 
Vic -- tors _ in the midst of strife;
Joy -- ful mu -- sic leads us sun -- ward 
In the tri -- umph song of life.
}



%%%%%   tune   %%%%%

\language "english"

hasChords     = ##f
hasDescant    = ##f

\header{
   fsTuneCredit = \markup { \wordwrap { Tune: HYMN TO JOY, 8 7 8 7 D; arr. from Ludwig van Beethoven, 1770-1827, by Edward Hodges, 1796-1867 } }
}

keyTime = {
    \time 4/4
    \numericTimeSignature
    \key g \major
}

Soprano = \relative c' {
  \voiceOne
  \keyTime
  \hideSlur
  b'4 b c d
| d c b a
| g g a b
| b4. a8 a2
| b4 b c d
| d c b a
| g g a b
| a4. g8 g2
| a4 a b g
| a b8 c b4 g
| a b8 c b4 a
| g a d,2
| b'4 b c d
| d c b a
| g g a b
| a4. g8 g2
\bar "|."
}

Alto = \relative c' {
  \voiceTwo
  \keyTime
  d4 d d d
| d e8 fs g4 d
| d d fs g
| g4. fs8 fs2
| g4 d e f
| f e d e
| d d fs g
| fs4. g8 g2
| fs4 d d g
| fs g8 fs g4 g
| fs fs fs ds
| e8 d cs4 d2
| d4 d e f
| f e d e
| d d fs g
| fs4. g8 g2
}

Tenor = \relative c {
  \voiceOne
  \keyTime
  g'4 g a b
| b a g fs
| g b c d
| d4. d8 d2
| d4 d c b
| g a b c
| b b c d
| c4. b8 b2
| d4 fs, g b
| c b8 a g4 b
| c b8 a b4 b
| b a8 g fs2
| g4 d' c b
| g a b c
| b b c d
| c4. b8 b2
}

Bass = \relative c {
  \voiceTwo
  \keyTime
  g'4 g g g
| d d d c
| b b a g
| d'4. d8 d2
| g4 g g g
| c, c c c
| d d d d
| d4. g8 g2
| d4 d d d
| d d d d
| d d ds b
| e a, d2
| g4 g g g
| c, c c c
| d d d d
| d4. g8 g2
}




%%%%%   BulletinHarmony template   %%%%%

#(set-global-staff-size 20)
#(set-default-paper-size "legal" 'portrait)
\header {
  fsHymnNumber = ""
}

\layout {
	\context { \Lyrics
		\override LyricText #'font-size = #1
	}
}

\layout {
	\context { \Score
		\remove "Bar_number_engraver"
	}
}

\score
{
  <<
		\new Staff = "treble" \with {
	}
    <<
		\clef "treble"
		\new Voice = "SopranoVoice" \Soprano
		\new Voice = "AltoVoice" \Alto
		\lyricsto SopranoVoice \new Lyrics \StanzaOne
		\lyricsto SopranoVoice \new Lyrics \StanzaTwo
		\lyricsto SopranoVoice \new Lyrics \StanzaThree
		\lyricsto SopranoVoice \new Lyrics \StanzaFour
	>>

		\new Staff = "bass" \with {
	}
    <<
		\clef "bass"
		\new Voice = "TenorVoice" \Tenor
		\new Voice = "BassVoice" \Bass
	>>

  >>
  
}
