%
% Generated by flexscore.php on 2015-11-30 20:41:42
%
% Score configuration:
% <?xml version="1.0"?>
% <AltoSax>
%   <instrumentName>E&#x266D; Alto Saxophone</instrumentName>
%   <staff1>t-defc'</staff1>
%   <staff3>ta-sefc'-aefc'</staff3>
%   <staff4>ta-tefc''</staff4>
%   <requires>Alto,Tenor,Bass|Keyboard</requires>
%   <showPartNames>true</showPartNames>
%   <stanzas>all</stanzas>
%   <showDescantLyrics>false</showDescantLyrics>
%   <showSubtitle>false</showSubtitle>
%   <useKeyboard>true</useKeyboard>
%   <showVocalMarkup>false</showVocalMarkup>
%   <lilypond>true</lilypond>
%   <staffSize>25</staffSize>
%   <lyricSize>1</lyricSize>
%   <paperSize>letter</paperSize>
%   <orientation>portrait</orientation>
%   <showMeasureNumbers>true</showMeasureNumbers>
%   <showHymnNumber>true</showHymnNumber>
%   <separateDescant>false</separateDescant>
%   <separateStanzas>false</separateStanzas>
%   <iPad>true</iPad>
%   <includeNotes>true</includeNotes>
%   <autoResizeTitle>true</autoResizeTitle>
%   <maxInlineStanzas>5</maxInlineStanzas>
%   <overflowLyricSize>0</overflowLyricSize>
%   <staff1Name>descant</staff1Name>
%   <staff2Name>chords</staff2Name>
%   <staff3Name>treble</staff3Name>
%   <staff4Name>bass</staff4Name>
%   <staff5Name>percussion</staff5Name>
%   <staff6Name>keyboard</staff6Name>
%   <hymnalID>CGH2010</hymnalID>
%   <number>261</number>
%   <textHymnalID>CGH2010</textHymnalID>
%   <textNumber>261</textNumber>
%   <tuneHymnalID>CGH2010</tuneHymnalID>
%   <tuneNumber>261</tuneNumber>
%   <instrument>AltoSax</instrument>
%   <hymnType>normal_flexscore</hymnType>
%   <hymnID/>
%   <hash>88abff</hash>
%   <hasSoprano>true</hasSoprano>
%   <hasAlto>true</hasAlto>
%   <hasTenor>true</hasTenor>
%   <hasBass>true</hasBass>
%   <useStanzas>StanzaOne StanzaTwo StanzaThree StanzaFour</useStanzas>
%   <inlineStanzas>4</inlineStanzas>
%   <keySignature>efmaj</keySignature>
%   <stanzaSpecificResponseLyrics>false</stanzaSpecificResponseLyrics>
% </AltoSax>
% 
\include "definitions.ly"


%%%%%   text   %%%%%

\header {
  title = \markup { \fontsize #-0.17 "Onward, Christian Soldiers" }
}

StanzaOne = \lyricmode {
 \set stanza = "1."  
On -- ward, Chris -- tian sol -- diers, 
march -- ing as to war, 
with the cross of Je -- sus
go -- ing on be -- fore! 
Christ, the roy -- al Mas -- ter, 
leads a -- gainst the foe; 
for -- ward in -- to bat -- tle,
see His ban -- ner go! 
%refrain
}

StanzaTwo = \lyricmode {
 \set stanza = "2."
At the sign of tri -- umph
Sa -- tan’s host doth flee; 
on, then, Chris -- tian sol -- diers, 
on to vic -- to -- ry! 
Hell’s foun -- da -- tions quiv -- er
at the shout of praise; 
Chris -- tians, lift your voic -- es, 
loud your an -- thems raise! 
%refrain end 
On -- ward Chris -- tian sol -- diers, 
march -- ing as to _ war, 
with the cross of Je -- sus
go -- ing on be -- fore! 
%endrefrain 
}

StanzaThree = \lyricmode {
 \set stanza = "3."
Like a might -- y ar -- my
moves the church of God; 
Chris -- tians, we are tread -- ing
where the saints have trod; 
we are not di -- vid -- ed; 
all one bod -- y we, 
one in hope and doc -- trine, 
one in char -- i -- ty.
%refrain
}

StanzaFour = \lyricmode {
 \set stanza = "4." 
On -- ward, then, ye peo -- ple,
join our hap -- py throng, 
blend with ours your voic -- es
in the tri -- umph song; 
glo -- ry, laud, and hon -- or
un -- to Christ the King; 
this through count -- less a -- ges
earth and an -- gels sing. 
%refrain
}


%%%%%   tune   %%%%%

\language "english"

hasChords     = ##f
hasDescant    = ##f

\header{
  fsTuneCredit = \markup { \wordwrap { MUSIC (ST. GERTRUDE 6.5.6.5 D with refrain): Arthur S. Sullivan, 1871} }
}

keyTime = {
   \time 4/4
   \numericTimeSignature
   \key ef \major
}

Soprano = \relative c' {
 \voiceOne
 \keyTime
 \hideSlur
   
    bf'4 bf bf bf 
|   bf4.( c8) bf2 
|   f4 f ef f 
|   g1 
|   ef4 g bf ef 
|   ef2 d 
|   c4 c g a 
|   bf1
|   f4 f bf f 
|   g4.( af8) g2 
|   bf4 bf ef bf 
|   c1 
|   c4 bf af bf 
|   c( bf) af( bf) 
|   c4 bf af g 
|   f1 \bar "||" 
|   ef4 ef ef ef 
|   ef( d8[ c]) d4( ef) 
|   f4 f f ef8[ f] 
|   g1 
|   bf4 bf ef d 
|   ef2 bf 
|   af4 g f4. ef8 
|   ef1 
  
\bar "|."
}

Alto = \relative c' {
 \voiceTwo
 \keyTime
 \hideSlur
   
    g'4 g g g 
|   af2 af 
|   d,4 d c d 
|   ef1 
|   ef4 ef ef ef 
|   f2 f 
|   ef4 ef ef ef 
|   d1
|   d4 d f d 
|   ef4.( f8) ef2 
|   ef4 ef ef ef 
|   ef1 
|   ef4 ef ef ef 
|   ef2 ef 
|   ef4 ef f ef 
|   d1 \bar "||"
|   bf4 bf bf bf 
|   bf2 bf 
|   bf4 bf bf bf 
|   bf1 
|   g'4 g af af 
|   g2 ef 
|   ef4 ef d4. ef8 
|   ef1 
  
\bar "|."
}

Tenor = \relative c {
 
 \keyTime
 \hideSlur
   
    ef4 g bf ef 
|   ef2 d 
|   bf4 bf bf bf 
|   bf1 
|   bf4 bf bf bf 
|   bf4.( c8) bf2
|   a4 a bf c 
|   bf1 
|   bf4 bf bf bf 
|   bf2 bf 
|   g4 g bf g 
|   af1
|   af4 g af g 
|   af( g) af( g) 
|   af4 g f f 
|   bf1 \bar "||" 
|   g4 g g g 
|   af2 af 
|   af4 af af af 
|   g( ef g bf)
|   ef4 ef bf bf 
|   bf2 bf 
|   c4. bf8 af4. g8 
|   g1
  
\bar "|."
}

Bass = \relative c {
 \voiceTwo
 \keyTime
 \hideSlur
  
    ef4 ef ef ef 
|   f2 bf,2 
|   af'4 af g f 
|   ef1 
|   g4 g g g 
|   f2 f 
|   f4 f f f 
|   bf,1 
|   bf4 bf d bf 
|   ef2 ef 
|   ef4 ef g ef 
|   af1
|   af4 ef c ef 
|   af( ef) c( ef) 
|   af,4 af af a! 
|   bf1 \bar "||" 
|   ef4 bf ef bf 
|   f'( bf,) f'( bf,) 
|   d4 bf d bf 
|   ef1 
|   ef4 ef f f 
|   g2 g, 
|   af4 f bf4. ef8 
|   ef1 
  
\bar "|."
}



%%%%%   AltoSax template   %%%%%

#(set-global-staff-size 25)
#(set-default-paper-size "letter" 'portrait)
\header {
  instrument = "E♭ Alto Saxophone"
  subtitle = ""
}

\layout {
	\context { \Lyrics
		\override LyricText #'font-size = #1
	}
}

\score
{
  <<
		\new Staff = "treble" \with {
		instrumentName = \markup { \column { "S" \line { "A" } } }
	}
    <<
		\clef "treble"
		\transpose ef c'
		\new Voice = "SopranoVoice" \removeWithTag #'vocalMarkup \Soprano
		\transpose ef c'
		\new Voice = "AltoVoice" \removeWithTag #'vocalMarkup \Alto
		\lyricsto SopranoVoice \new Lyrics \StanzaOne
		\lyricsto SopranoVoice \new Lyrics \StanzaTwo
		\lyricsto SopranoVoice \new Lyrics \StanzaThree
		\lyricsto SopranoVoice \new Lyrics \StanzaFour
	>>

		\new Staff = "bass" \with {
		instrumentName = #"T"
	}
    <<
		\clef "treble"
		\transpose ef c''
		\new Voice = "TenorVoice" \removeWithTag #'vocalMarkup \Tenor
	>>

  >>
}
