%
% Generated by flexscore.php on 2017-08-03 10:38:40
%
% Score configuration:
% <?xml version="1.0"?>
% <Accompaniment>
%   <staff1>t-dcc</staff1>
%   <staff2>c-ccc</staff2>
%   <staff3>ta-scc-acc</staff3>
%   <!-- combine when lilypond partcombine/lyric bug fixed -->
%   <staff4>ba-tcc-bcc</staff4>
%   <staff5>p</staff5>
%   <requires>Alto,Tenor,Bass|Keyboard</requires>
%   <showVocalMarkup>true</showVocalMarkup>
%   <useKeyboard>true</useKeyboard>
%   <useHarmonyChords>true</useHarmonyChords>
%   <stanzas>all</stanzas>
%   <showPartNames>false</showPartNames>
%   <lilypond>true</lilypond>
%   <staffSize>29</staffSize>
%   <lyricSize>-2</lyricSize>
%   <paperSize>letter</paperSize>
%   <orientation>portrait</orientation>
%   <showMeasureNumbers>true</showMeasureNumbers>
%   <showHymnNumber>true</showHymnNumber>
%   <showSubtitle>true</showSubtitle>
%   <separateDescant>false</separateDescant>
%   <separateStanzas>false</separateStanzas>
%   <iPad>true</iPad>
%   <includeNotes>true</includeNotes>
%   <autoResizeTitle>true</autoResizeTitle>
%   <maxInlineStanzas>5</maxInlineStanzas>
%   <overflowLyricSize>0</overflowLyricSize>
%   <staff1Name>descant</staff1Name>
%   <staff2Name>chords</staff2Name>
%   <staff3Name>treble</staff3Name>
%   <staff4Name>bass</staff4Name>
%   <staff5Name>percussion</staff5Name>
%   <staff6Name>keyboard</staff6Name>
%   <lyricSizeIncrement>-3</lyricSizeIncrement>
%   <staffSizeIncrement>4</staffSizeIncrement>
%   <hymnalID>AM2013</hymnalID>
%   <number>281</number>
%   <textHymnalID>AM2013</textHymnalID>
%   <textNumber>281</textNumber>
%   <tuneHymnalID>AM2013</tuneHymnalID>
%   <tuneNumber>281</tuneNumber>
%   <instrument>Accompaniment</instrument>
%   <hymnType>normal_flexscore</hymnType>
%   <hymnID/>
%   <hash>2ed6fd</hash>
%   <hasSoprano>true</hasSoprano>
%   <hasAlto>true</hasAlto>
%   <hasTenor>true</hasTenor>
%   <hasBass>true</hasBass>
%   <useStanzas>StanzaOne StanzaTwo StanzaThree StanzaFour StanzaFive</useStanzas>
%   <inlineStanzas>5</inlineStanzas>
%   <keySignature>efmaj</keySignature>
%   <stanzaSpecificResponseLyrics>false</stanzaSpecificResponseLyrics>
% </Accompaniment>
% 
\include "definitions.ly"


%%%%%   text   %%%%%

StanzaOne = \lyricmode {
  \set stanza = "1"  
’Tis good, Lord, to _ be _ here,
thy glo -- ry _ fills the _ night;
thy face and _ gar -- ments, _ like the _ sun,
shine with un -- _ bor -- rowed light.
}

StanzaTwo = \lyricmode {
  \set stanza = "2"
’Tis good, Lord, to _ be _ here,
thy beau -- ty _ to be -- _ hold,
where Mo -- ses _ and E -- _ li -- jah _ stand,
thy mes -- sen -- _ gers of old.
}

StanzaThree = \lyricmode {
  \set stanza = "3"
Ful -- fill -- er of _ the _ past,
pro -- mise of _ things to _ be,
we hail thy _ bod -- y _ glo -- ri -- _ fied,
and our re -- _ demp -- tion see.
}

StanzaFour = \lyricmode {
  \set stanza = "4" 
Be -- fore we taste _ of _ death,
we see thy _ king -- dom _ come;
we fain would _ hold the _ vi -- sion _ bright,
and make this _ hill our home.
}

StanzaFive = \lyricmode {
  \set stanza = "5" 
’Tis good, Lord, to _ be _ here,
yet we may _ not re -- _ main;
but since thou _ bidst us _ leave the _ mount,
come with us _ to the plain.
}


%%%%%   tune   %%%%%

\language "english"

hasChords     = ##f
hasDescant    = ##f

\header {
   fsTuneCredit = \markup { \wordwrap { Music (CARLISLE, SM): Charles Lockhart (1745-1815) } }
}

keyTime = {
    \time 4/4
    \override Staff.TimeSignature #'stencil = ##f
    \key ef \major
    \partial 4
    \set Timing.beamExceptions = #'()
    \set Timing.baseMoment = #(ly:make-moment 1 4)
    \set Timing.beatStructure = #'(1 1 1 1)
}

Soprano = \relative c' {
  \voiceOne
  \keyTime
  \hideSlur
  
    ef4
  | bf' ef, g8 f ef d
  | ef2. \breathe ef4
  | af bf8 c bf4 ef,8 af
  | g4( f2) \bar "||" \break f4
  | g f8 ef af4 g8 f
  | bf4 af8 g c4 \breathe d
  | ef ef,8 af g4 f
  | ef2. \bar "|."
}

Alto = \relative c' {
  \voiceTwo
  \keyTime
  \hideSlur
  
    ef4
  | bf c c bf
  | bf2. ef4
  | ef ef ef ef
  | ef( d2) \bar "||" d4
  | ef8 d c4 f8 ef d4
  | g8 f ef4 ef f
  | ef ef8 f ef4 d
  | ef2. \bar "|."
}

Tenor = \relative c {
  \voiceOne
  \keyTime
  \hideSlur
  
    g'4
  | f g bf8 af g f
  | g2. \breathe g4
  | af g8 af bf4 c
  | bf2. \bar "||" bf4
  | bf af c bf
  | bf ef8 df c4 \breathe bf
  | bf g8 c bf4 bf8 af
  | g2. \bar "|."
}

Bass = \relative c {
  \voiceTwo
  \keyTime
  \hideSlur
  
    ef4
  | d c af bf
  | ef2. ef8 df
  | c4 bf8 af g4 af
  | bf2. \bar "||" bf4
  | ef af8 g f4 bf8 af
  | g4 c8 bf af4 af
  | g c,8 af bf4 bf
  | ef2. \bar "|."
}



%%%%%   Accompaniment template   %%%%%

#(set-global-staff-size 29)
#(set-default-paper-size "letter" 'portrait)
\header {
}

\layout {
	\context { \Lyrics
		\override LyricText #'font-size = #-2
	}
}

\score
{
  <<
		\new Staff = "treble" \with {
	}
    <<
		\clef "treble"
		\new Voice = "SopranoVoice" \Soprano
		\new Voice = "AltoVoice" \Alto
		\lyricsto SopranoVoice \new Lyrics \StanzaOne
		\lyricsto SopranoVoice \new Lyrics \StanzaTwo
		\lyricsto SopranoVoice \new Lyrics \StanzaThree
		\lyricsto SopranoVoice \new Lyrics \StanzaFour
		\lyricsto SopranoVoice \new Lyrics \StanzaFive
	>>

		\new Staff = "bass" \with {
	}
    <<
		\clef "bass"
		\new Voice = "TenorVoice" \Tenor
		\new Voice = "BassVoice" \Bass
	>>

  >>
}
