%
% Generated by flexscore.php on 2018-10-13 12:54:38
%
% Score configuration:
% <?xml version="1.0"?>
% <BulletinHarmony>
%   <instrument>BulletinHarmony</instrument>
%   <staff3>ta-scc-acc</staff3>
%   <staff4>ba-tcc-bcc</staff4>
%   <stanzas>all</stanzas>
%   <showHymnNumber>false</showHymnNumber>
%   <showMeasureNumbers>false</showMeasureNumbers>
%   <showVocalMarkup>true</showVocalMarkup>
%   <staffSize>20</staffSize>
%   <lyricSize>1</lyricSize>
%   <paperSize>legal</paperSize>
%   <iPad>false</iPad>
%   <useKeyboard>true</useKeyboard>
%   <includeNotes>false</includeNotes>
%   <showPartNames>false</showPartNames>
%   <lilypond>true</lilypond>
%   <orientation>portrait</orientation>
%   <showSubtitle>true</showSubtitle>
%   <separateDescant>false</separateDescant>
%   <separateStanzas>false</separateStanzas>
%   <autoResizeTitle>true</autoResizeTitle>
%   <maxInlineStanzas>5</maxInlineStanzas>
%   <overflowLyricSize>0</overflowLyricSize>
%   <staff1Name>descant</staff1Name>
%   <staff2Name>chords</staff2Name>
%   <staff3Name>treble</staff3Name>
%   <staff4Name>bass</staff4Name>
%   <staff5Name>percussion</staff5Name>
%   <staff6Name>keyboard</staff6Name>
%   <hymnalID>AAHH2001</hymnalID>
%   <number>337</number>
%   <textHymnalID>AAHH2001</textHymnalID>
%   <textNumber>337</textNumber>
%   <tuneHymnalID>AAHH2001</tuneHymnalID>
%   <tuneNumber>337</tuneNumber>
%   <hymnType>normal_flexscore</hymnType>
%   <hymnID/>
%   <hash>811c5e</hash>
%   <hasSoprano>true</hasSoprano>
%   <hasAlto>true</hasAlto>
%   <hasTenor>true</hasTenor>
%   <hasBass>true</hasBass>
%   <useStanzas>StanzaOne StanzaTwo StanzaThree StanzaFour</useStanzas>
%   <inlineStanzas>4</inlineStanzas>
%   <keySignature>efmaj</keySignature>
%   <stanzaSpecificResponseLyrics>false</stanzaSpecificResponseLyrics>
% </BulletinHarmony>
% 
\include "definitions.ly"


%%%%%   text   %%%%%

\header{
   title = \markup { \fontsize #0 "The Church’s One Foundation" }
}

StanzaOne = \lyricmode {
  \set stanza = "1."
  The Church -- ’s one foun -- da -- tion Is Je -- sus Christ her Lord,
  She is His new cre -- a -- tion By wa -- ter and the word;
  From heav’n He came and sought her To be His ho -- ly bride;
  With His own blood He bought her, And for her life He died.
}

StanzaTwo = \lyricmode {
  \set stanza = "2."
  E -- lect from ev -- ’ry na -- tion, Yet one o’er all the earth,
  Her char -- ter of sal -- va -- tion, One Lord, one faith, one birth;
  One ho -- ly name she bless -- es, Par -- takes one ho -- ly food,
  And to one hope she press -- es, With ev -- ’ry grace en -- dued.
}

StanzaThree = \lyricmode {
  \set stanza = "3."
  ’Mid toil and trib -- u -- la -- tion, And tu -- mult of her war,
  She waits the con -- sum -- ma -- tion Of peace for -- ev -- er -- more;
  Till with the vi -- sion glo -- rious, Her long -- ing eyes are blest,
  And the great Church vic -- to -- rious Shall be the Church at rest.
}

StanzaFour = \lyricmode {
  \set stanza = "4."
  Yet she on earth hath un -- ion With God, the Three in One,
  And mys -- tic sweet com -- mu -- nion With those whose rest is won;
  O hap -- py ones and ho -- ly! Lord, give us grace that we
  Like them, the meek and low -- ly, On high may dwell with Thee.
}


%%%%%   tune   %%%%%

\language "english"

hasChords     = ##f
hasDescant    = ##f

\header{
   fsTuneCredit = \markup { Tune (AURELIA 7 6 7 6 D): Samuel S. Wesley, 1810-1876 }
}

keyTime = {
    \time 4/4
    \numericTimeSignature
    \key ef \major
    \partial 4
}

Soprano = \relative g' {
  \voiceOne
  \keyTime
  \hideSlur
    g4
  | g g af g
  | g2 f4 ef
  | ef c' bf af
  | g2. \bar "" af4
  | bf ef ef d
  | d2 c4 bf
  | af bf g ef
  | f2. \bar "" f4
  | g af bf c
  | c2 bf4 ef
  | ef4. d8 c4 g
  | af2. \bar "" f4
  | g g af g
  | g2 f4 ef
  | ef f ef d
  | ef2. \bar "|."
  }

Alto = \relative c' {
  \voiceTwo
  \keyTime
  \hideSlur
    ef4
  | ef ef ef ef 
  | ef2 d4 ef
  | c ef ef d
  | ef2. \bar "" d4
  | ef ef ef f
  | f2 ef4 g
  | g f ef ef
  | d2. \bar "" d4
  | ef d ef ef
  | ef2 ef4 g
  | g4. g8 g4 g
  | f2. \bar "" f4
  | ef ef ef ef
  | c2 c4 c
  | c c bf bf
  | bf2. \bar "|."
  }

Tenor = \relative g {
  \voiceOne
  \keyTime
  \hideSlur
    bf4
  | bf bf c bf
  | bf2 bf4 bf
  | f f g bf
  | bf2. \bar "" bf4
  | bf bf b b
  | b2 c4 d
  | ef bf bf a
  | bf2. \bar "" bf4
  | bf bf bf af
  | af2 bf4 c
  | c4. b8 c4 c
  | c2. \bar "" bf4
  | bf bf c bf
  | bf2 af4 af
  | af af f af
  | g2. \bar "|."
  }

Bass = \relative c {
  \voiceTwo
  \keyTime
  \hideSlur
    ef4
  | ef ef ef ef
  | bf2 af4 g
  | af af bf bf
  | ef2. \bar "" f4
  | g g g g,
  | af2 af4 bf
  | c d ef c
  | bf2. \bar "" bf4
  | ef f g af
  | af2 g4 c,
  | g'4. f8 ef4 e
  | f2. \bar "" d4
  | ef ef ef ef
  | af,2 af4 af
  | f f bf bf
  | ef2. \bar "|."
  }

%%%%%   BulletinHarmony template   %%%%%

#(set-global-staff-size 20)
#(set-default-paper-size "legal" 'portrait)
\header {
  fsHymnNumber = ""
}

\layout {
	\context { \Lyrics
		\override LyricText #'font-size = #1
	}
}

\layout {
	\context { \Score
		\remove "Bar_number_engraver"
	}
}

\score
{
  <<
		\new Staff = "treble" \with {
	}
    <<
		\clef "treble"
		\new Voice = "SopranoVoice" \Soprano
		\new Voice = "AltoVoice" \Alto
		\lyricsto SopranoVoice \new Lyrics \StanzaOne
		\lyricsto SopranoVoice \new Lyrics \StanzaTwo
		\lyricsto SopranoVoice \new Lyrics \StanzaThree
		\lyricsto SopranoVoice \new Lyrics \StanzaFour
	>>

		\new Staff = "bass" \with {
	}
    <<
		\clef "bass"
		\new Voice = "TenorVoice" \Tenor
		\new Voice = "BassVoice" \Bass
	>>

  >>
  
}
