%
% Generated by flexscore.php on 2017-02-15 06:09:35
%
% Score configuration:
% <?xml version="1.0"?>
% <BulletinHarmony>
%   <instrument>BulletinHarmony</instrument>
%   <staff3>ta-scc-acc</staff3>
%   <staff4>ba-tcc-bcc</staff4>
%   <stanzas>all</stanzas>
%   <showHymnNumber>false</showHymnNumber>
%   <showMeasureNumbers>false</showMeasureNumbers>
%   <showSubtitle>false</showSubtitle>
%   <showVocalMarkup>true</showVocalMarkup>
%   <staffSize>20</staffSize>
%   <lyricSize>1</lyricSize>
%   <paperSize>legal</paperSize>
%   <iPad>false</iPad>
%   <useKeyboard>true</useKeyboard>
%   <includeNotes>false</includeNotes>
%   <showPartNames>false</showPartNames>
%   <lilypond>true</lilypond>
%   <orientation>portrait</orientation>
%   <separateDescant>false</separateDescant>
%   <separateStanzas>false</separateStanzas>
%   <autoResizeTitle>true</autoResizeTitle>
%   <maxInlineStanzas>5</maxInlineStanzas>
%   <overflowLyricSize>0</overflowLyricSize>
%   <staff1Name>descant</staff1Name>
%   <staff2Name>chords</staff2Name>
%   <staff3Name>treble</staff3Name>
%   <staff4Name>bass</staff4Name>
%   <staff5Name>percussion</staff5Name>
%   <staff6Name>keyboard</staff6Name>
%   <hymnalID>BH1991</hymnalID>
%   <number>340</number>
%   <textHymnalID>BH1991</textHymnalID>
%   <textNumber>340</textNumber>
%   <tuneHymnalID>BH1991</tuneHymnalID>
%   <tuneNumber>340</tuneNumber>
%   <hymnType>normal_flexscore</hymnType>
%   <hymnID/>
%   <hash>2b3b6a</hash>
%   <hasSoprano>true</hasSoprano>
%   <hasAlto>true</hasAlto>
%   <hasTenor>true</hasTenor>
%   <hasBass>true</hasBass>
%   <useStanzas>StanzaOne StanzaTwo StanzaThree StanzaFour</useStanzas>
%   <inlineStanzas>4</inlineStanzas>
%   <keySignature>dmaj</keySignature>
%   <stanzaSpecificResponseLyrics>false</stanzaSpecificResponseLyrics>
% </BulletinHarmony>
% 
\include "definitions.ly"


%%%%%   text   %%%%%

\header {
   title = \markup { \fontsize #0 "He Hideth My Soul" }
}

StanzaOne = \lyricmode {
  \set stanza = "1."  
A won -- der -- ful Sav -- ior is Je -- sus my Lord,
A won -- der -- ful Sav -- ior to me;
He hid -- eth my soul in the cleft of the rock,
Where riv -- ers of plea -- sure I see.
}

StanzaTwo = \lyricmode {
  \set stanza = "2."
A won -- der -- ful Sav -- ior is Je -- sus my Lord,
He tak -- eth my bur -- den a -- way;
He hold -- eth me up, and I shall not be moved,
He giv -- eth me strength as my day.
%refrain end
He hid -- eth my soul in the cleft of the rock
That shad -- ows a dry, thirst -- y land;
He hid -- eth my life in the depths of His love,
And cov -- ers me there with His hand,
And cov -- ers me there with His hand.
%endrefrain
}

StanzaThree = \lyricmode {
  \set stanza = "3."
With num -- ber -- less bless -- ings each mo -- ment He crowns,
And filled with His full -- ness di -- vine,
I sing in my rap -- ture, oh, glo -- ry to God
For such a Re -- deem -- er as mine!
}

StanzaFour = \lyricmode {
  \set stanza = "4." 
When clothed in His bright -- ness, trans -- port -- ed I rise
To meet Him in clouds of the sky,
His per -- fect sal -- va -- tion, His won -- der -- ful love
I’ll shout with the mil -- lions on high.
}


%%%%%   tune   %%%%%

\language "english"

hasChords     = ##f
hasDescant    = ##f

\header{
   fsTuneCredit = \markup { 
     \wordwrap { MUSIC (KIRKPATRICK 11.8.11.8. with Refrain): William J. Kirkpatrick, 1838-1921 } }
}

keyTime = {
    \time 6/8
    \numericTimeSignature
    \key d \major
    \partial 8
}

Soprano = \relative c' {
  \voiceOne
  \hideSlur
  \keyTime
    a'8
  | a8. g16 fs8 fs e d
  | b'8. b16 b8 a4 a8
  | a8. g16 fs8 fs g fs
  | e4.~ e4 \bar "" a8
  | a8. g16 fs8 fs e d
  | b'8. b16 b8 d4 b8
  | a8. a16 a8 a g e
  | d4.~ d4 \bar "." a'8 \noBreak
  | cs8. cs16 cs8 cs4 b16 cs
  | d8. cs16 b8 a4 a8
  | g fs g e b' a
  | fs4.~ fs4 \bar "" a8 \noBreak
  | d8. d16 d8 d4 d16 d
  | e8. d16 d8 d4
%remove when separateStanzas=true
 \bar "|" \break
%endremove
    b8
  | a8. a16 a8 a a a
  | a4.~ a4 b8
  | a8. fs16 d8 g8. cs,16 cs8
  | d4.~ d4 \bar "|."
}

Alto = \relative c' {
  \voiceTwo
  \hideSlur
  \keyTime
    fs8 
  | fs8. e16 d8 d d d
  | g8. g16 g8 fs4 fs8
  | fs8. e16 d8 d e d
  | cs4.~ cs4 \bar "" g'8
  | fs8. e16 d8 d d d
  | g8. g16 g8 g4 g8
  | fs8. fs16 fs8 cs cs cs
  | d4.~ d4 \bar "." a'8 \noBreak
  | g8. g16 g8 g4 g16 g
  | fs8. a16 g8 fs4 fs8
  | e8 ds e cs cs cs
  | d4.~ d4 \bar "" fs8 \noBreak
  | fs8. fs16 fs8 fs4 fs16 fs
  | g8. g16 g8 g4
%remove when separateStanzas=true
 \bar "|" \break
%endremove
    g8
  | fs8. fs16 fs8 e fs g
  | fs4( g8 a4) g8
  | fs8. d16 d8 cs8. a16 a8
  | a4.~ a4 \bar "|."
}

Tenor = \relative c {
  \voiceOne
  \hideSlur
  \keyTime
    a'8
  | a8. a16 a8 a g fs
  | d'8. d16 d8 d4 a8
  | a8. a16 a8 a a a
  | a4.~ a4 \bar "" cs8
  | d8. a16 a8 a g fs
  | d'8. d16 d8 b4 d8
  | d8. a16 fs8 e e g
  | fs4.~ fs4 \bar "." a8 \noBreak
  | e'8. e16 e8 e4 a,16 a
  | a8. a16 d8 d4 a8
  | a a a a a a
  | a4.~ a4 \bar "" a8 \noBreak
  | a8. a16 a8 a4 a16 a
  | b8. b16 b8 b4
%remove when separateStanzas=true
 \bar "|" \break
%endremove
    d8
  | d8. d16 d8 cs d e
  | d4( cs8 d4) d8
  | d8. a16 fs8 e8. g16 g8
  | fs4.~ fs4 \bar "|."
}

Bass = \relative c {
  \voiceTwo
  \hideSlur
  \keyTime
    d8 
  | d8. d16 d8 d d d
  | g,8. g16 g8 d'4 d8
  | d8. d16 d8 d cs d
  | a4.~ a4 \bar "" a8
  | d8. d16 d8 d d d
  | g,8. g16 g8 g4 g8
  | a8. a16 a8 a a a
  | d4.~ d4 \bar "." a'8 \noBreak
  | a8. a16 a8 a4 a16 a
  | d,8. d16 d8 d4 d8
  | a a a a a a
  | d4.~ d4 \bar "" d8 \noBreak
  | d8. d16 d8 d4 d16 d
  | g8. g16 g8 g4
%remove when separateStanzas=true
 \bar "|" \break
%endremove
    g8
  | a8. a16 a8 a, a a
  | d4( e8 fs4) g,8
  | a8. a16 a8 a8. a16 a8
  | d4.~ d4 \bar "|."
}


%%%%%   BulletinHarmony template   %%%%%

#(set-global-staff-size 20)
#(set-default-paper-size "legal" 'portrait)
\header {
  subtitle = ""
  fsHymnNumber = ""
}

\layout {
	\context { \Lyrics
		\override LyricText #'font-size = #1
	}
}

\layout {
	\context { \Score
		\remove "Bar_number_engraver"
	}
}

\score
{
  <<
		\new Staff = "treble" \with {
	}
    <<
		\clef "treble"
		\new Voice = "SopranoVoice" \Soprano
		\new Voice = "AltoVoice" \Alto
		\lyricsto SopranoVoice \new Lyrics \StanzaOne
		\lyricsto SopranoVoice \new Lyrics \StanzaTwo
		\lyricsto SopranoVoice \new Lyrics \StanzaThree
		\lyricsto SopranoVoice \new Lyrics \StanzaFour
	>>

		\new Staff = "bass" \with {
	}
    <<
		\clef "bass"
		\new Voice = "TenorVoice" \Tenor
		\new Voice = "BassVoice" \Bass
	>>

  >>
}
