%
% Generated by flexscore.php on 2018-06-02 08:56:00
%
% Score configuration:
% <?xml version="1.0"?>
% <Accompaniment>
%   <staff1>t-dcc</staff1>
%   <staff2>c-ccc</staff2>
%   <staff3>ta-scc-acc</staff3>
%   <!-- combine when lilypond partcombine/lyric bug fixed -->
%   <staff4>ba-tcc-bcc</staff4>
%   <staff5>p</staff5>
%   <requires>Alto,Tenor,Bass|Keyboard</requires>
%   <showVocalMarkup>true</showVocalMarkup>
%   <useKeyboard>true</useKeyboard>
%   <useHarmonyChords>true</useHarmonyChords>
%   <stanzas>all</stanzas>
%   <showPartNames>false</showPartNames>
%   <lilypond>true</lilypond>
%   <staffSize>25</staffSize>
%   <lyricSize>1</lyricSize>
%   <paperSize>letter</paperSize>
%   <orientation>portrait</orientation>
%   <showMeasureNumbers>true</showMeasureNumbers>
%   <showHymnNumber>true</showHymnNumber>
%   <showSubtitle>true</showSubtitle>
%   <separateDescant>false</separateDescant>
%   <separateStanzas>false</separateStanzas>
%   <iPad>true</iPad>
%   <includeNotes>true</includeNotes>
%   <autoResizeTitle>true</autoResizeTitle>
%   <maxInlineStanzas>5</maxInlineStanzas>
%   <overflowLyricSize>0</overflowLyricSize>
%   <staff1Name>descant</staff1Name>
%   <staff2Name>chords</staff2Name>
%   <staff3Name>treble</staff3Name>
%   <staff4Name>bass</staff4Name>
%   <staff5Name>percussion</staff5Name>
%   <staff6Name>keyboard</staff6Name>
%   <hymnalID>AAHH2001</hymnalID>
%   <number>398</number>
%   <textHymnalID>AAHH2001</textHymnalID>
%   <textNumber>398</textNumber>
%   <tuneHymnalID>AAHH2001</tuneHymnalID>
%   <tuneNumber>398</tuneNumber>
%   <instrument>Accompaniment</instrument>
%   <hymnType>normal_flexscore</hymnType>
%   <hymnID/>
%   <hash>0bf74f</hash>
%   <hasSoprano>true</hasSoprano>
%   <hasAlto>true</hasAlto>
%   <hasTenor>true</hasTenor>
%   <hasBass>true</hasBass>
%   <useStanzas>StanzaOne StanzaTwo StanzaThree StanzaFour</useStanzas>
%   <inlineStanzas>4</inlineStanzas>
%   <keySignature>efmaj</keySignature>
%   <stanzaSpecificResponseLyrics>false</stanzaSpecificResponseLyrics>
% </Accompaniment>
% 
\include "definitions.ly"


%%%%%   text   %%%%%

\header{
   title = \markup { \fontsize #-1.53 "In Christ There Is No East or West" }
}

StanzaOne = \lyricmode {
  \set stanza = "1."  
  In Christ there is no east or west,
  In Him no south or north,
  But one great fel -- low -- ship of love
  Through -- out the whole wide earth.
}

StanzaTwo = \lyricmode {
  \set stanza = "2."
  In Him shall true hearts ev -- ’ry -- where
  Their high com -- mu -- nion find;
  His ser -- vice is the gold -- en cord
  Close -- bind -- ing hu -- man -- kind.
}

StanzaThree = \lyricmode {
  \set stanza = "3."
  Join hands then, broth -- ers of the faith,
  What -- e'er your race may be;
  Who serves my Fa -- ther as a son
  Is sure -- ly kin to me.
}

StanzaFour = \lyricmode {
  \set stanza = "4." 
  In Christ now meet both east and west,
  In Him meet south and north;
  All Christ -- ly souls are one in Him
  Through -- out the whole wide earth.
}

%%%%%   tune   %%%%%

\language "english"

hasChords     = ##f
hasDescant    = ##f

\header{
   fsTuneCredit = \markup { Tune (ST. PETER, CM): Alexander R. Reinagle, 1799-1877 }
}

keyTime = {
    \time 4/4
    \numericTimeSignature
    \key ef \major
    \partial 4
}

Soprano = \relative c'' {
  \voiceOne
  \keyTime
  \hideSlur
    bf4
  | ef d c bf
  | bf af g g 
  | f ef af g
  | f2. \bar "" g4
  | af g c bf 
  | bf af g ef
  | g f ef d
  | ef2. \bar "|."
}

Alto = \relative c' {
  \voiceTwo
  \keyTime
  \hideSlur
    ef4
  | g g ef ef
  | f d ef ef 
  | c8 d ef4 d ef
  | d2. ef4
  | ef ef ef ef 
  | ef f ef c
  | ef c bf bf
  | bf2. \bar "|."
}

Tenor = \relative c' {
  \voiceOne
  \keyTime
  \hideSlur
    g4
  | bf bf af bf
  | bf bf bf bf 
  | c bf bf bf
  | bf2. bf4
  | af bf c ef 
  | c d c g
  | bf af g f8 af
  | g2. \bar "|."
}

Bass = \relative c {
  \voiceTwo
  \keyTime
  \hideSlur
    ef4
  | ef g af g
  | d bf ef ef 
  | af g f ef 
  | bf2. ef8 df
  | c4 bf af g 
  | f bf c c
  | g af bf bf
  | ef2. \bar "|."
}



%%%%%   Accompaniment template   %%%%%

#(set-global-staff-size 25)
#(set-default-paper-size "letter" 'portrait)
\header {
}

\layout {
	\context { \Lyrics
		\override LyricText #'font-size = #1
	}
}

\score
{
  <<
		\new Staff = "treble" \with {
	}
    <<
		\clef "treble"
		\new Voice = "SopranoVoice" \Soprano
		\new Voice = "AltoVoice" \Alto
		\lyricsto SopranoVoice \new Lyrics \StanzaOne
		\lyricsto SopranoVoice \new Lyrics \StanzaTwo
		\lyricsto SopranoVoice \new Lyrics \StanzaThree
		\lyricsto SopranoVoice \new Lyrics \StanzaFour
	>>

		\new Staff = "bass" \with {
	}
    <<
		\clef "bass"
		\new Voice = "TenorVoice" \Tenor
		\new Voice = "BassVoice" \Bass
	>>

  >>
  
}
