%
% Generated by flexscore.php on 2015-02-02 09:50:10
%
% Score configuration:
% <?xml version="1.0"?>
% <BulletinHarmony>
%   <instrument>BulletinHarmony</instrument>
%   <staff3>ta-scc-acc</staff3>
%   <staff4>ba-tcc-bcc</staff4>
%   <stanzas>all</stanzas>
%   <showHymnNumber>false</showHymnNumber>
%   <showMeasureNumbers>false</showMeasureNumbers>
%   <showSubtitle>false</showSubtitle>
%   <showVocalMarkup>true</showVocalMarkup>
%   <staffSize>18</staffSize>
%   <lyricSize>0</lyricSize>
%   <paperSize>legal</paperSize>
%   <iPad>false</iPad>
%   <useKeyboard>true</useKeyboard>
%   <includeNotes>false</includeNotes>
%   <showPartNames>false</showPartNames>
%   <lilypond>true</lilypond>
%   <orientation>portrait</orientation>
%   <separateDescant>false</separateDescant>
%   <separateStanzas>false</separateStanzas>
%   <autoResizeTitle>true</autoResizeTitle>
%   <maxInlineStanzas>5</maxInlineStanzas>
%   <overflowLyricSize>0</overflowLyricSize>
%   <staff1Name>descant</staff1Name>
%   <staff2Name>chords</staff2Name>
%   <staff3Name>treble</staff3Name>
%   <staff4Name>bass</staff4Name>
%   <staff5Name>percussion</staff5Name>
%   <staff6Name>keyboard</staff6Name>
%   <lyricSizeIncrement>-1</lyricSizeIncrement>
%   <staffSizeIncrement>-2</staffSizeIncrement>
%   <hymnalID>AAHH2001</hymnalID>
%   <number>455</number>
%   <textHymnalID>AAHH2001</textHymnalID>
%   <textNumber>455</textNumber>
%   <tuneHymnalID>AAHH2001</tuneHymnalID>
%   <tuneNumber>455</tuneNumber>
%   <hymnType>normal_flexscore</hymnType>
%   <hymnID/>
%   <hash>8cfe1a</hash>
%   <hasSoprano>true</hasSoprano>
%   <hasAlto>true</hasAlto>
%   <hasTenor>true</hasTenor>
%   <hasBass>true</hasBass>
%   <useStanzas>StanzaOne StanzaTwo StanzaThree</useStanzas>
%   <inlineStanzas>3</inlineStanzas>
%   <keySignature>bfmaj</keySignature>
%   <stanzaSpecificResponseLyrics>false</stanzaSpecificResponseLyrics>
% </BulletinHarmony>
% 
\include "definitions.ly"


%%%%%   text   %%%%%

\header {
   title = \markup { \fontsize #0 "Just a Closer Walk with Thee" }
}
slurOff = { \set ignoreMelismata = ##t }
slurOn = { \unset ignoreMelismata }

StanzaOne = \lyricmode {
  \set stanza = "1."  
I am weak but Thou art strong;
Je -- sus, keep me from all wrong;
I’ll be sat -- is -- fied as long
As I walk, \slurOff let me walk close to \slurOn Thee.
}

StanzaTwo = \lyricmode {
  \set stanza = "2."
\slurOn Through this world of toil and snares,
If I fal -- ter, Lord, who cares?
Who with me my bur -- den shares?
None but Thee, dear Lord, none but Thee.
%refrain end
Just a clos -- er walk with Thee,
Grant it, Je -- sus, if You please?
Dai -- ly walk -- ing close to Thee,
Let it be, dear Lord, let it be.
%endrefrain
}

StanzaThree = \lyricmode {
  \set stanza = "3."
When my fee -- ble life is o’er,
Time for me will be no more;
Guide me gent -- ly, safe -- ly o’er
To Thy king -- dom shore, to Thy shore.
}


%%%%%   tune   %%%%%

\language "english"

hasChords     = ##f
hasDescant    = ##f

\header{
   fsTuneCredit = \markup { 
     \wordwrap { Tune (CLOSER WALK 777 8): Anonymous } }
}

keyTime = {
    \time 4/4
    \numericTimeSignature
    \key bf \major
    \set Timing.beamExceptions = #'()
    \set Timing.baseMoment = #(ly:make-moment 1 4)
    \set Timing.beatStructure = #'(1 1 1 1)
}

ref = {
    \once \override Score.RehearsalMark #'self-alignment-X = #LEFT
    \mark \markup \small \italic "Refrain"
}

Soprano = \relative c' {
  \voiceOne
  \hideSlur
  \keyTime
  | f4. fs8 g d f e 
  | ef1
  | c'4. bf8 a f g bf
  | g( f ~ f2.)
  | d'4. d8 d bf c d
  | c( bf ~ bf2) \bar "" bf8 g
  | f4 \tieDashed f8 ~ f f4 g8 a
  | bf1
%remove when separateStanzas=true  
  \bar "||"
%endremove  
  | \ref f4. fs8 g d f e 
  | ef1
  | c'4. bf8 a f g bf
  | \tieSolid g( f ~ f2.)
  | d'4. d8 d bf c d
  | \tieSolid c( bf ~ bf2) \bar "" bf8 g
  | f4 \tieDashed f8 ~ f f4 g8 a
  | bf1 \bar "|."
}

Alto = \relative c' {
  \voiceTwo
  \hideSlur
  \keyTime
  | d4. d8 d bf bf bf  
  | bf2( c)
  | ef4. ef8 ef ef ef ef
  | d1
  | f4. f8 f d ef f
  | ef2( cs4) \bar "" cs8 cs
  | d4 \tieDashed d8 ~ d ef4 ef8 ef 
  | d1
%remove when separateStanzas=true  
  \bar "||"
%endremove
  | d4. d8 d bf bf bf  
  | bf2( c)
  | ef4. ef8 ef ef ef ef
  | d1
  | f4. f8 f d ef f
  | ef2( cs4) \bar "" cs8 cs
  | d4 \tieDashed d8 ~ d ef4 ef8 ef 
  | d1 \bar "|."
}

Tenor = \relative c {
  \voiceOne
  \hideSlur
  \keyTime
  | bf'4. bf8 bf f f g 
  | g2( a)
  | a4. bf8 c a a g 
  | bf1
  | bf4. a8 af af af af
  | g2. \bar "" g8 bf
  | bf4 \tieDashed bf8 ~ bf a4 g8 f
  | f1
%remove when separateStanzas=true
    \bar "||"
%endremove
  | bf4. bf8 bf f f g 
  | g2( a)
  | a4. bf8 c a a g 
  | bf1
  | bf4. a8 af af af af
  | g2. \bar "" g8 bf
  | bf4 \tieDashed bf8 ~ bf a4 g8 f
  | f1 \bar "|."
}

Bass = \relative c {
  \voiceTwo
  \hideSlur
  \keyTime
  | bf4. bf8 bf bf d df  
  | c2( f) 
  | f4. f8 f f f f
  | bf,1
  | bf4. bf8 bf bf bf bf
  | ef2( e4) \bar "" e8 e
  | f4 \tieDashed f8 ~ f f4 f8 f
  | bf,1
%remove when separateStanzas=true
   \bar "||"
%endremove
  | bf4. bf8 bf bf d df  
  | c2( f) 
  | f4. f8 f f f f
  | bf,1
  | bf4. bf8 bf bf bf bf
  | ef2( e4) \bar "" e8 e
  | f4 \tieDashed f8 ~ f f4 f8 f
  | bf,1 \bar "|."
}


%%%%%   BulletinHarmony template   %%%%%

#(set-global-staff-size 18)
#(set-default-paper-size "legal" 'portrait)
\header {
  subtitle = ""
  fsHymnNumber = ""
}

\layout {
	\context { \Lyrics
		\override LyricText #'font-size = #0
	}
}

\layout {
	\context { \Score
		\remove "Bar_number_engraver"
	}
}

\score
{
  <<
		\new Staff = "treble" \with {
	}
    <<
		\clef "treble"
		\new Voice = "SopranoVoice" \Soprano
		\new Voice = "AltoVoice" \Alto
		\lyricsto SopranoVoice \new Lyrics \StanzaOne
		\lyricsto SopranoVoice \new Lyrics \StanzaTwo
		\lyricsto SopranoVoice \new Lyrics \StanzaThree
	>>

		\new Staff = "bass" \with {
	}
    <<
		\clef "bass"
		\new Voice = "TenorVoice" \Tenor
		\new Voice = "BassVoice" \Bass
	>>

  >>
}
