%
% Generated by flexscore.php on 2018-07-01 19:35:36
%
% Score configuration:
% <?xml version="1.0"?>
% <BulletinHarmony>
%   <instrument>BulletinHarmony</instrument>
%   <staff3>ta-scc-acc</staff3>
%   <staff4>ba-tcc-bcc</staff4>
%   <stanzas>all</stanzas>
%   <showHymnNumber>false</showHymnNumber>
%   <showMeasureNumbers>false</showMeasureNumbers>
%   <showVocalMarkup>true</showVocalMarkup>
%   <staffSize>20</staffSize>
%   <lyricSize>1</lyricSize>
%   <paperSize>legal</paperSize>
%   <iPad>false</iPad>
%   <useKeyboard>true</useKeyboard>
%   <includeNotes>false</includeNotes>
%   <showPartNames>false</showPartNames>
%   <lilypond>true</lilypond>
%   <orientation>portrait</orientation>
%   <showSubtitle>true</showSubtitle>
%   <separateDescant>false</separateDescant>
%   <separateStanzas>false</separateStanzas>
%   <autoResizeTitle>true</autoResizeTitle>
%   <maxInlineStanzas>5</maxInlineStanzas>
%   <overflowLyricSize>0</overflowLyricSize>
%   <staff1Name>descant</staff1Name>
%   <staff2Name>chords</staff2Name>
%   <staff3Name>treble</staff3Name>
%   <staff4Name>bass</staff4Name>
%   <staff5Name>percussion</staff5Name>
%   <staff6Name>keyboard</staff6Name>
%   <hymnalID>AAHH2001</hymnalID>
%   <number>569</number>
%   <textHymnalID>AAHH2001</textHymnalID>
%   <textNumber>569</textNumber>
%   <tuneHymnalID>AAHH2001</tuneHymnalID>
%   <tuneNumber>569</tuneNumber>
%   <hymnType>normal_flexscore</hymnType>
%   <hymnID/>
%   <hash>6886b6</hash>
%   <hasSoprano>true</hasSoprano>
%   <hasAlto>true</hasAlto>
%   <hasTenor>true</hasTenor>
%   <hasBass>true</hasBass>
%   <useStanzas>StanzaOne StanzaTwo StanzaThree StanzaFour</useStanzas>
%   <inlineStanzas>4</inlineStanzas>
%   <keySignature>fmaj</keySignature>
%   <stanzaSpecificResponseLyrics>false</stanzaSpecificResponseLyrics>
% </BulletinHarmony>
% 
\include "definitions.ly"


%%%%%   text   %%%%%


\header {
  title = \markup { \fontsize #0 "Revive Us Again" }
}

slurOff = { \set ignoreMelismata = ##t }
slurOn = { \unset ignoreMelismata }

StanzaOne = \lyricmode {
 \set stanza = "1."  

We praise Thee, O God, for the Son of Thy love,
For Je -- sus who died and is now gone a -- bove. 
%refrain

}

StanzaTwo = \lyricmode {
 \set stanza = "2."

We praise Thee, O God, for Thy Spir -- it of light, 
\slurOff Who has \slurOn shown us our Sav -- ior and scat -- tered our night. 
%refrain end 
Hal -- le -- lu -- jah, Thine the glo -- ry! 
Hal -- le -- lu -- jah, A -- men! 
Hal -- le -- lu -- jah, Thine the glo -- ry! 
Re -- vive us a -- gain. 
%endrefrain

}

StanzaThree = \lyricmode {
 \set stanza = "3."
 
All glo -- ry and praise to the Lamb that was slain, 
\slurOff Who has \slurOn borne all our sins and has cleansed ev -- ’ry stain. 
%refrain

}

StanzaFour = \lyricmode {
 \set stanza = "4." 

Re -- vive us a -- gain— fill each heart with Thy love; 
\slurOff May each \slurOn soul be re -- kin -- dled with fire from a -- bove.
%refrain 

}

%%%%%   tune   %%%%%

\language "english"

hasChords     = ##f
hasDescant    = ##f

\header{
  fsTuneCredit = \markup { \wordwrap { Tune (REVIVE US AGAIN 11 11 with refrain): John J. Husband, 1760-1825 } }
}

keyTime = {
   \time 3/4
   \numericTimeSignature
   \key f \major
   \partial 4
}

Soprano = \relative c' {
 \voiceOne
 \keyTime
 \hideSlur
  
   c4
|  f f f 
|  f2 f8[ g] 
|  a4 a a 
|  a2 \slurDashed f8[( a])
|  c4 c c 
|  d c a
|  a g g 
|  g2 \bar "||" \bar "" c8.[ c16] 
|  d4 c a8.[ g16] 
|  f4 f c'8.[ c16] 
|  d4 c a 
|  g2 c8.[ c16] 
|  d4 c a8.[ g16] 
|  f4 f a 
|  bf a g 
|  f2 
  
\bar "|."
}

Alto = \relative c' {
 \voiceTwo
 \keyTime
 \hideSlur
  
   c4 
|  c c c 
|  c2 c8[ e] 
|  f4 f f 
|  f2 \tieDashed f8[~ f8] 
|  f4 f f 
|  f f f 
|  f e e 
|  e2 \bar "||" f8.[ f16] 
|  f4 f f8.[ c16] 
|  c4 c f8.[ f16] 
|  f4 f f 
|  e2 f8.[ f16] 
|  f4 f f8.[ c16] 
|  c4 c f 
|  f f e 
|  c2 
  
\bar "|."
}

Tenor = \relative c {
 \voiceOne
 \keyTime
 \hideSlur
  
   a'4 
|  a a a 
|  a2 c8[ c] 
|  c4 c c 
|  c2 \slurDashed a8([ c]) 
|  a4 a a 
|  bf a c 
|  c c c 
|  c2 \bar "||" a8.[ a16] 
|  bf4 a c8.[ bf16] 
|  a4 a a8.[ a16] 
|  bf4 a c 
|  c2 a8.[ a16] 
|  bf4 a c8.[ bf16] 
|  a4 a c 
|  d c bf 
|  a2
  
\bar "|."
}

Bass = \relative c {
 \voiceTwo
 \keyTime
 \hideSlur
  
    f4 
|   f c a 
|   f2 a'8[ g] 
|   f4 c a 
|   f2 \tieDashed f'8[~ f] 
|   f4 f f 
|   f f f 
|   c c c 
|   c2 \bar "||" f8.[ f16] 
|   bf4 f f8.[ f16] 
|   f4 f f8.[ f16] 
|   f4 f f 
|   c2 f8.[ f16] 
|   bf4 f f8.[ f16] 
|   f4 f f 
|   bf, c c 
|   f2 
  
\bar "|."
}



%%%%%   BulletinHarmony template   %%%%%

#(set-global-staff-size 20)
#(set-default-paper-size "legal" 'portrait)
\header {
  fsHymnNumber = ""
}

\layout {
	\context { \Lyrics
		\override LyricText #'font-size = #1
	}
}

\layout {
	\context { \Score
		\remove "Bar_number_engraver"
	}
}

\score
{
  <<
		\new Staff = "treble" \with {
	}
    <<
		\clef "treble"
		\new Voice = "SopranoVoice" \Soprano
		\new Voice = "AltoVoice" \Alto
		\new Lyrics \lyricsto "SopranoVoice" \StanzaOne
		\new Lyrics \lyricsto "SopranoVoice" \StanzaTwo
		\new Lyrics \lyricsto "SopranoVoice" \StanzaThree
		\new Lyrics \lyricsto "SopranoVoice" \StanzaFour
	>>

		\new Staff = "bass" \with {
	}
    <<
		\clef "bass"
		\new Voice = "TenorVoice" \Tenor
		\new Voice = "BassVoice" \Bass
	>>

  >>
  
}
